# Generated by Django 5.0 on 2023-12-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='contents',
            field=models.TextField(),
        ),
    ]
