# Generated by Django 5.0 on 2023-12-19 08:37

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogmodel_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='contents',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
