# Generated by Django 5.0 on 2023-12-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_contents_blogmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='blog'),
        ),
    ]
